Gabor ML - Problem 16

-Clarice Mottet

Outline:
-generate training data
    -x_i multivariate normal distribution (mean zero, covariance diagonal (1/1...d))
    -y_i sum(x_i) + e_i where e_i standard normal random variable
-predict y as a linear function wTX of X
-measure performance by mean squared error R(w) = E(wTX-Y)^2
-write program that learns vector w by OLS
-write program that learns vector w by GD
-write program that learns vector w by SGD
-compare performance by mean squared error and running time for multiple n and d and step size n_t

In [3]:
#libraries
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt

path_out_ = r'/home/clarice/Documents/VSCode/Term2_Gabor_ML/homework4/GaborML_problem16/outputs'
random.seed(123)

In [ ]:
#functions

def generate_data(n, d):

    #covariance matrix
    cov = np.identity(d)    
    for i in range(d):
        cov[i,i] = 1/(i+1)

    #x
    x = np.random.multivariate_normal(np.zeros(d), cov, n)

    #y
    y = np.zeros(n)
    e = np.random.normal(0, 1, n)
    for i in range(n):
        y[i] = sum(x[i]) + e[i]

    return x, y
        
        
            


In [24]:
n = 3
d = 4

cov = np.identity(d)
# print(cov)

for i in range(d):
    cov[i,i] = 1/(i+1)
    # print(cov[i,i])

x = np.random.multivariate_normal(np.zeros(d), cov, n)
print(x)

for i in range(n):
    sum_x = sum(x[i])
    print("sum_x",sum_x)

e_i = np.random.normal(0, 1)
print(e_i)

e = np.random.normal(0, 1, n)
print("e",e)
print(e[1])
    

[[ 0.19975299  1.24871933  0.2077985   0.20460925]
 [ 2.43382726 -0.66190346  1.18392529  0.76469286]
 [-1.41255396 -0.31107659  0.58370829 -0.73354036]]
sum_x 1.8608800605303506
sum_x 3.720541935450088
sum_x -1.873462620586202
-0.7691376089075934
e [-0.53095965  1.16457974  0.53451655]
1.1645797395643673
